spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bdot
    username: postgres
    password: u92
  jpa:
    hibernate:
      ddl-auto: none
security:
  oauth2:
    resource:
      filter-order: 3
server:
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-password: password
---
spring:
  profiles: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bdot
    username: postgres
    password: u92
  jpa:
    hibernate:
      ddl-auto: none